[package]
name = "batched-fn"
version = "0.1.0"
authors = ["epwalsh <epwalsh10@gmail.com>"]
edition = "2018"

[lib]
name = "batched_fn"
path = "src/lib.rs"

[[example]]
name = "example"

[dependencies]
tokio = { version = "0.2.13", features = ["sync", "time", "rt-core"] }
once_cell = { version = "1.3.1" }

[dev-dependencies]
tokio = { version = "*", features = ["sync", "time", "rt-threaded", "macros"] }
